# This workflow will download a prebuilt Ruby version, install dependencies, and  run linters
name: Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  es-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn install

      - name: Run ESLint
        run: yarn lint

